import { describe, expect, test } from "vitest";
import { canonicalizeJcsJson } from "../../packages/domain-pack-contracts/src/jcs.ts";

// Fixed examples from RFC 8785 §§3.2.2–3.2.3 and Appendix B, not generated by this package.
// https://www.rfc-editor.org/rfc/rfc8785
describe("RFC 8785/JCS serialization", () => {
  test("matches the RFC primitive and property-order example", () => {
    const input = JSON.parse(String.raw`{
      "numbers": [333333333.33333329, 1E30, 4.50,
                  2e-3, 0.000000000000000000000000001],
      "string": "\u20ac$\u000F\u000aA'\u0042\u0022\u005c\\\"\/",
      "literals": [null, true, false]
    }`) as Parameters<typeof canonicalizeJcsJson>[0];
    const expected = String.raw`{"literals":[null,true,false],"numbers":[333333333.3333333,1e+30,4.5,0.002,1e-27],"string":"€$\u000f\nA'B\"\\\\\"/"}`;
    expect(canonicalizeJcsJson(input)).toBe(expected);
  });

  test("sorts non-ASCII property names by UTF-16 code units", () => {
    const input = JSON.parse(String.raw`{
      "\u20ac": "Euro Sign",
      "\r": "Carriage Return",
      "\ufb33": "Hebrew Letter Dalet With Dagesh",
      "1": "One",
      "\ud83d\ude00": "Emoji: Grinning Face",
      "\u0080": "Control",
      "\u00f6": "Latin Small Letter O With Diaeresis"
    }`) as Record<string, string>;
    const output = canonicalizeJcsJson(input);
    const values = [
      "Carriage Return",
      "One",
      "Control",
      "Latin Small Letter O With Diaeresis",
      "Euro Sign",
      "Emoji: Grinning Face",
      "Hebrew Letter Dalet With Dagesh",
    ];
    expect(
      values.map((value) => output.indexOf(JSON.stringify(value))),
    ).toEqual(
      [...values.map((value) => output.indexOf(JSON.stringify(value)))].sort(
        (a, b) => a - b,
      ),
    );
  });

  test("recurses through nested objects without reordering arrays", () => {
    expect(
      canonicalizeJcsJson({
        z: [
          { b: 2, a: 1 },
          { d: 4, c: 3 },
        ],
        a: "value",
      }),
    ).toBe('{"a":"value","z":[{"a":1,"b":2},{"c":3,"d":4}]}');
  });

  test.each([
    [-0, "0"],
    [1e30, "1e+30"],
    [Number.MIN_VALUE, "5e-324"],
    [Number("333333333.33333329"), "333333333.3333333"],
  ])("serializes RFC number sample %s as %s", (input, expected) => {
    expect(canonicalizeJcsJson(input)).toBe(expected);
  });

  test("rejects non-finite numbers and lone surrogates", () => {
    for (const invalid of [
      Number.NaN,
      Number.POSITIVE_INFINITY,
      "\ud800",
      { "\udfff": "x" },
    ]) {
      expect(() => canonicalizeJcsJson(invalid)).toThrow(TypeError);
    }
  });
});
